encrypt-type: 0  # 0:standard, 1:guomi
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - 110.64.72.12:20200  # node listen_ip:channel_listen_port
                    - 110.64.72.12:20201
                    - 110.64.72.12:20202
                    - 110.64.72.12:20203
 
channel-service:
  group-id: 1 # The specified group to which the SDK connects
  org-id: fisco # agency name

user-key:
  user-key: 3bed914595c159cbce70ec5fb6aff3d6797e0c5ee5a7a9224a21cae8932d84a4 # user key 

contract-addr:
  contract-addr: 07efc57183fd752df8cbe0acbddeb283cc4e4aa7